version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: espumred_anticipos_app
    ports:
      - "5050:5050"  # Puerto de la aplicación (actualizado según el Dockerfile)
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_TIMEZONE=America/Bogota
      - DB_HOST=db
      - DB_PORT=3306  # Puerto interno de MySQL (dentro de la red Docker)
      - DB_DATABASE=db_anticipos  # Nombre de la base de datos
      - DB_USERNAME=root
      - DB_PASSWORD=Espumas2025*.
      - APP_LOCALE=es
      - APP_FALLBACK_LOCALE=es
    depends_on:
      db:
        condition: service_healthy
    networks:
      - anticipos-network
    volumes:
      - ./:/app  # Montar toda la aplicación
      - /app/vendor  # Evitar sobrescribir las dependencias instaladas
      - ./storage:/app/storage  # Asegurar que storage sea persistente
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: espumred_anticipos_db
    ports:
      - "3030:3306"  # Puerto externo 3030 como solicitado
    environment:
      - MYSQL_DATABASE=db_anticipos  # Corregido para coincidir con DB_DATABASE
      - MYSQL_ROOT_PASSWORD=Espumas2025*.
      - MYSQL_ROOT_HOST=%  # Permitir conexiones desde cualquier host
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql  # Persistir datos de la base de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pEspumas2025*."]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - anticipos-network
    restart: unless-stopped

networks:
  anticipos-network:
    driver: bridge

volumes:
  db-data:  # Volumen para persistir datos de MySQL